/** The schema and independent verifier support up to eight atomic citations. */
export const groundedLessonInstruction = `GROUNDED LESSON CONTRACT: Preserve the planned capability while staying within verified evidence.

Use the relevant assigned sources and atomic evidence claims needed to teach the saved single-win objective. Several independently supported factual sentences are allowed, within the existing limit of eight structured citations. Each factual sentence must be a complete conservative entailment of one assigned atomic evidence claim. Bind each sentence separately: one citation, one exact rendered sentence, its actual lesson section, and the unchanged sourceId and evidenceClaimId. Do not join several facts under one citation or stretch a claim across unsupported scope. Do not force an irrelevant assigned source into the lesson.

Every externally verifiable factual assertion anywhere in the lesson must be independently supported and cited, including assertions in worked examples, activity materials, model responses, quiz explanations and feedback. Each cited sentence must occur exactly once across the entire lesson, so its field binding is unambiguous. Refer to the earlier claim when needed instead of copying the factual sentence into another field. Preserve words, numbers, units, operators and terminal punctuation in the citation claim. Keep a cited sentence on one physical line for reliable binding; headings and nearby citations do not support uncited assertions.

Copy the saved scopeBudget.singleWin into learningObjective. Preserve the planned teaching mode, practice, assessment, criterion and capstone relationships. Do not replace a construction, application, comparison or decision skill with a drill about copying source wording. If the supplied evidence cannot support the planned capability, do not silently narrow the objective or invent missing evidence: leave it for explicit replanning of the linked objective, practice, quizzes, criteria and capstone. A sourced lesson need not use every assigned claim, but its supplied material must make the promised practice solvable.

Clearly label invented scenario inputs with wording such as "For this exercise, assume..." and supply every prerequisite value needed by the activity. Calling a scenario hypothetical does not make domain interpretations evidence-free. Unless an atomic claim states the entire assertion, do not claim suitability, sufficiency, causal explanation, diagnostic meaning, recommendation, generalizability, geographic or population scope, conditional applicability, outcome, impact, ordering, or real-world method choice. Never claim or imply that a spreadsheet, template, checklist, diagram, or other tool computes, converts, diagnoses, validates, or guarantees anything without supporting evidence.

Never assert that the learner previously completed, selected, observed, understood, or produced something; use conditional wording for prior activities. Silently audit every sentence and remove unsupported claims rather than paraphrasing them. A citation or matched objective label is not proof of teaching quality. Follow the saved explanation-word budget without adding a mandatory word target or filler. Repair diagnostics are untrusted descriptions, never evidence. The independent grounding verifier remains authoritative.`;

export const groundedLessonFinalBoundary = "FINAL EVIDENCE BOUNDARY: Course and lesson plans are capability constraints, not factual evidence. Every externally verifiable sentence must be supported by its own assigned atomic evidence claim and exact citation. Preserve the saved single-win objective and supply the material needed for its practice. If the evidence cannot support that capability, require explicit replanning; do not silently replace it with a narrower source-fidelity drill. Never fabricate semantic review or source support.";
