import test from 'node:test';import assert from 'node:assert/strict';
import {buildOnRunner,createExecutor} from '../../scripts/build-release-image.mjs';
const sha='b'.repeat(40),digest='sha256:'+'d'.repeat(64);
const env={EXPECTED_SHA:sha,GITHUB_SHA:sha,GITHUB_REF:'refs/heads/main',GITHUB_REPOSITORY:'Victor-CS-Core/Filosage',GITHUB_ACTOR:'github-actions[bot]',GITHUB_TOKEN:'synthetic_private_token',GITHUB_RUN_ID:'123',GITHUB_RUN_ATTEMPT:'1',PUBLIC_SITE_URL:'https://filosage.com'};
const headers=value=>`HTTP/2 200\r\ncontent-type: application/vnd.oci.image.index.v1+json\r\ndocker-content-digest: ${value}\r\n\r\n`;
function fixture(change={}){const calls=[];const execute=(command,args,input)=>{calls.push({command,args,input});if(command==='git')return sha;if(command==='node')return 'COURSE_PIPELINE_V2=true\n';if(command==='curl'&&args.at(-1).includes('/token?'))return JSON.stringify({token:'synthetic-registry-token'});if(command==='curl'&&args.includes('--write-out'))return '404';if(command==='curl')return headers(digest);if(args[0]==='push')return `tag: digest: ${digest} size: 42`;return '';};return {calls,execute:(...args)=>change.execute?change.execute(execute,...args):execute(...args)};}
const curls=f=>f.calls.filter(c=>c.command==='curl');
test('one runtime amd64 GHCR build, private stdin credentials, immutable push/readback match',()=>{const f=fixture();assert.equal(buildOnRunner(env,f.execute),digest);const build=f.calls.filter(c=>c.command==='docker'&&c.args[0]==='build');assert.equal(build.length,1);assert.ok(build[0].args.includes('runtime'));assert.ok(build[0].args.includes('linux/amd64'));assert.ok(build[0].args.includes('ghcr.io/victor-cs-core/filosage:'+sha+'-123-1'));assert.ok(build[0].args.includes('SITE_VERSION='+sha));assert.ok(build[0].args.includes('COURSE_PIPELINE_V2=true'));const login=f.calls.find(c=>c.command==='docker'&&c.args[0]==='login');assert.deepEqual(login.args,['login','ghcr.io','--username','github-actions[bot]','--password-stdin']);assert.equal(login.input,env.GITHUB_TOKEN);assert.ok(f.calls.every(c=>!c.args.join(' ').includes(env.GITHUB_TOKEN)&&!c.args.join(' ').includes('synthetic-registry-token')));assert.ok(!f.calls.some(c=>c.command==='az'));for(const c of curls(f)){assert.equal(c.args[0],'--disable');assert.equal(c.args[c.args.indexOf('--config')+1],'-');assert.equal(c.args[c.args.indexOf('--proto')+1],'=https');assert.match(c.args.at(-1),/^https:\/\/ghcr\.io\/(token\?service=ghcr\.io&scope=repository:victor-cs-core\/filosage:|v2\/victor-cs-core\/filosage\/manifests\/)/);}});
test('tag absence, authenticated readback and anonymous public readback are distinct ordered checks',()=>{const f=fixture();buildOnRunner(env,f.execute);const order=f.calls.map(c=>c.command==='docker'?c.args[0]:c.command==='curl'?c.args.at(-1).replace(/^https:\/\/ghcr\.io\//,''):c.command);const push=order.indexOf('push');const tagCheck=order.indexOf(`v2/victor-cs-core/filosage/manifests/${sha}-123-1`);assert.ok(tagCheck>=0&&tagCheck<order.indexOf('build'));assert.ok(order.lastIndexOf(`v2/victor-cs-core/filosage/manifests/${sha}-123-1`)>push);assert.ok(order.indexOf(`v2/victor-cs-core/filosage/manifests/${digest}`)>push);const tokens=curls(f).filter(c=>c.args.at(-1).includes('/token?'));assert.deepEqual(tokens.map(c=>c.args.at(-1).split(':').at(-1)),['pull,push','pull,push','pull']);assert.equal(tokens[0].input,`user = "x-access-token:${env.GITHUB_TOKEN}"\n`);assert.equal(tokens[2].input,'');const manifests=curls(f).filter(c=>c.args.at(-1).includes('/manifests/'));for(const c of manifests){assert.equal(c.input,'header = "Authorization: Bearer synthetic-registry-token"\n');assert.match(c.args[c.args.indexOf('--header')+1],/^Accept: .*application\/vnd\.oci\.image\.index\.v1\+json.*application\/vnd\.docker\.distribution\.manifest\.v2\+json$/);}});
test('wrong source, ref, repository or unsafe credentials prevent every registry command',()=>{for(const patch of [{GITHUB_SHA:'a'.repeat(40)},{GITHUB_REF:'refs/heads/other'},{GITHUB_REPOSITORY:'other/Filosage'},{GITHUB_TOKEN:''},{GITHUB_TOKEN:'synthetic"\nurl = "https://example.com'},{GITHUB_ACTOR:'bad actor'},{PUBLIC_SITE_URL:'https://other.example'}]){const f=fixture();assert.throws(()=>buildOnRunner({...env,...patch},f.execute));assert.ok(!f.calls.some(c=>c.command==='curl'||c.command==='docker'));}});
test('existing or unverifiable tag prevents login, build and push',()=>{for(const status of ['200','401','403','500','']){const f=fixture({execute:(base,c,a,i)=>c==='curl'&&a.includes('--write-out')?status:base(c,a,i)});assert.throws(()=>buildOnRunner(env,f.execute));assert.ok(!f.calls.some(c=>c.command==='docker'));}const failed=fixture({execute:(base,c,a,i)=>{if(c==='curl'&&a.at(-1).includes('/token?'))throw Error('denied');return base(c,a,i);}});assert.throws(()=>buildOnRunner(env,failed.execute));assert.ok(!failed.calls.some(c=>c.command==='docker'));});
test('push failure, ambiguous digests, readback mismatch or non-public package fail without rebuild',()=>{const other='sha256:'+'e'.repeat(64);const scenarios={push:(c,a)=>c==='docker'&&a[0]==='push'?Error('failure'):null,twoPushDigests:(c,a)=>c==='docker'&&a[0]==='push'?`digest: ${digest} size: 1\ndigest: ${other} size: 2`:null,readback:(c,a)=>c==='curl'&&a.includes('--dump-header')&&!a.at(-1).includes('/manifests/sha256:')?headers(other):null,duplicateHeader:(c,a)=>c==='curl'&&a.includes('--dump-header')?headers(digest)+headers(digest):null,privatePackage:(c,a)=>c==='curl'&&a.at(-1).endsWith(':pull')?Error('denied'):null,publicMismatch:(c,a)=>c==='curl'&&a.at(-1).includes('/manifests/sha256:')?headers(other):null,unsafeRegistryToken:(c,a)=>c==='curl'&&a.at(-1).includes('/token?')?JSON.stringify({token:'x"\nurl = "https://example.com'}):null};for(const [name,override] of Object.entries(scenarios)){const f=fixture({execute:(base,c,a,i)=>{const value=override(c,a);if(value instanceof Error)throw value;return value??base(c,a,i);}});assert.throws(()=>buildOnRunner(env,f.execute),undefined,name);assert.ok(f.calls.filter(c=>c.command==='docker'&&c.args[0]==='build').length<=1,name);}});
test('failure diagnostics identify safe stage and numeric exit without child output credentials or arguments',()=>{const logs=[];const execute=createExecutor({},()=>({status:17,signal:null,stdout:'private-token',stderr:'private-log',error:Error('private-error')}),v=>logs.push(v));assert.throws(()=>execute('docker',['login','private-argument'],'private-token'),/Build command failed/);assert.deepEqual(logs,[{operation:'docker-login',status:'started'},{operation:'docker-login',status:'failed',exitCode:17,signalNumber:null}]);assert.equal(JSON.stringify(logs).includes('private'),false);});
test('registry diagnostics name each curl stage without URLs or credentials',()=>{const logs=[];const f=fixture();const execute=createExecutor({},(command,args,options)=>({status:0,signal:null,stdout:f.execute(command,args,options.input)}),v=>logs.push(v));buildOnRunner(env,execute);const stages=logs.filter(l=>l.status==='started').map(l=>l.operation);assert.deepEqual(stages,['checkout-source','registry-token','registry-tag-check','docker-login','manifest','docker-build','docker-push','registry-token','registry-digest','registry-public-token','registry-public-check']);assert.equal(JSON.stringify(logs).includes('ghcr'),false);});

test('real capability stdout passes every manifest build argument independently',async()=>{
 const {execFileSync}=await import('node:child_process');
 const output=execFileSync(process.execPath,['scripts/release-capabilities.mjs','environment'],{encoding:'utf8'});
 const lines=output.trim().split(String.fromCharCode(10));assert.equal(lines.length,15);
 const f=fixture({execute:(base,c,a,i)=>c==='node'?output:base(c,a,i)});buildOnRunner(env,f.execute);
 const args=f.calls.find(c=>c.command==='docker'&&c.args[0]==='build').args;
 for(const line of lines)assert.ok(args.includes(line));
 assert.equal(args.filter(a=>a==='--build-arg').length,17);
});

test('actual CLI writes a real LF-delimited GITHUB_ENV digest and removes private Docker config',async()=>{
 const {mkdtempSync,writeFileSync,readFileSync,readdirSync,rmSync}=await import('node:fs');
 const {tmpdir}=await import('node:os');const {join,resolve}=await import('node:path');const {spawnSync}=await import('node:child_process');
 const dir=mkdtempSync(join(tmpdir(),'runner-build-contract-'));const output=join(dir,'github-env');
 const program=`#!${process.execPath}
const {basename}=require('node:path');const command=basename(process.argv[1]);const args=process.argv.slice(2);
if(command==='git')console.log(process.env.EXPECTED_SHA);
else if(command==='curl'){
 require('node:fs').readFileSync(0);
 if(args.at(-1).includes('/token?'))console.log(JSON.stringify({token:'synthetic-registry-token'}));
 else if(args.includes('--write-out'))process.stdout.write('404');
 else process.stdout.write('HTTP/2 200\\r\\ndocker-content-digest: '+process.env.FIXTURE_DIGEST+'\\r\\n\\r\\n');
}else if(args[0]==='push')console.log('tag: digest: '+process.env.FIXTURE_DIGEST+' size: 42');
`;
 try{
  for(const command of ['git','curl','docker'])writeFileSync(join(dir,command),program,{mode:0o700});
  const result=spawnSync(process.execPath,[resolve('scripts/build-release-image.mjs')],{encoding:'utf8',env:{...process.env,...env,PATH:dir+':'+process.env.PATH,RUNNER_TEMP:dir,GITHUB_ENV:output,FIXTURE_DIGEST:digest},timeout:10000});
  assert.equal(result.status,0,result.stderr);const data=readFileSync(output);assert.equal(data.at(-1),10);
  assert.deepEqual(data.toString().split(String.fromCharCode(10)),['EXPECTED_IMAGE_DIGEST='+digest,'']);
  for(const secret of [env.GITHUB_TOKEN,'synthetic-registry-token']){assert.equal(result.stdout.includes(secret),false);assert.equal(result.stderr.includes(secret),false);}
  assert.ok(!readdirSync(dir).some(name=>name.startsWith('release-docker-')));
 }finally{rmSync(dir,{recursive:true,force:true});}
});
