FROM node:22-bookworm-slim AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM dependencies AS builder
ARG NEXT_PUBLIC_SITE_URL
ARG SITE_VERSION
ARG FLASHCARD_DECKS_ENABLED=false
ARG FLASHCARD_AI_GENERATION_ENABLED=false
ARG LESSON_VISUALS_ENABLED=false
ARG COMMAND_CENTER_ENABLED=false
ARG COMMAND_CENTER_DRAFTS_ENABLED=false
ARG NEXT_PUBLIC_COMMAND_CENTER_V2=false
ARG COURSE_PIPELINE_V2=true
ARG COURSE_VALIDATION_V2=true
ARG COURSE_REPAIR_V2=true
ARG COURSE_LABS_V2=false
ARG COURSE_VISUALS_V2=false
ARG COURSE_PUBLICATION_V2=true
ARG COURSE_PIPELINE_SHADOW_MODE=false
ARG COURSE_PIPELINE_V2_OWNER_ONLY=true
ARG COURSE_PIPELINE_V2_COHORT_PERCENT=0
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV SITE_VERSION=$SITE_VERSION
ENV FLASHCARD_DECKS_ENABLED=$FLASHCARD_DECKS_ENABLED
ENV FLASHCARD_AI_GENERATION_ENABLED=$FLASHCARD_AI_GENERATION_ENABLED
ENV LESSON_VISUALS_ENABLED=$LESSON_VISUALS_ENABLED
ENV COMMAND_CENTER_ENABLED=$COMMAND_CENTER_ENABLED
ENV COMMAND_CENTER_DRAFTS_ENABLED=$COMMAND_CENTER_DRAFTS_ENABLED
ENV NEXT_PUBLIC_COMMAND_CENTER_V2=$NEXT_PUBLIC_COMMAND_CENTER_V2
ENV COURSE_PIPELINE_V2=$COURSE_PIPELINE_V2
ENV COURSE_VALIDATION_V2=$COURSE_VALIDATION_V2
ENV COURSE_REPAIR_V2=$COURSE_REPAIR_V2
ENV COURSE_LABS_V2=$COURSE_LABS_V2
ENV COURSE_VISUALS_V2=$COURSE_VISUALS_V2
ENV COURSE_PUBLICATION_V2=$COURSE_PUBLICATION_V2
ENV COURSE_PIPELINE_SHADOW_MODE=$COURSE_PIPELINE_SHADOW_MODE
ENV COURSE_PIPELINE_V2_OWNER_ONLY=$COURSE_PIPELINE_V2_OWNER_ONLY
ENV COURSE_PIPELINE_V2_COHORT_PERCENT=$COURSE_PIPELINE_V2_COHORT_PERCENT
COPY . .
RUN node scripts/release-capabilities.mjs check-environment && npm run build

FROM dependencies AS production-dependencies
RUN npm prune --omit=dev

FROM node:22-bookworm-slim AS runtime
ARG SITE_VERSION
ARG FLASHCARD_DECKS_ENABLED=false
ARG FLASHCARD_AI_GENERATION_ENABLED=false
ARG LESSON_VISUALS_ENABLED=false
ARG COMMAND_CENTER_ENABLED=false
ARG COMMAND_CENTER_DRAFTS_ENABLED=false
ARG NEXT_PUBLIC_COMMAND_CENTER_V2=false
ARG COURSE_PIPELINE_V2=true
ARG COURSE_VALIDATION_V2=true
ARG COURSE_REPAIR_V2=true
ARG COURSE_LABS_V2=false
ARG COURSE_VISUALS_V2=false
ARG COURSE_PUBLICATION_V2=true
ARG COURSE_PIPELINE_SHADOW_MODE=false
ARG COURSE_PIPELINE_V2_OWNER_ONLY=true
ARG COURSE_PIPELINE_V2_COHORT_PERCENT=0
LABEL org.opencontainers.image.revision=$SITE_VERSION
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV SITE_VERSION=$SITE_VERSION
ENV FLASHCARD_DECKS_ENABLED=$FLASHCARD_DECKS_ENABLED
ENV FLASHCARD_AI_GENERATION_ENABLED=$FLASHCARD_AI_GENERATION_ENABLED
ENV LESSON_VISUALS_ENABLED=$LESSON_VISUALS_ENABLED
ENV COMMAND_CENTER_ENABLED=$COMMAND_CENTER_ENABLED
ENV COMMAND_CENTER_DRAFTS_ENABLED=$COMMAND_CENTER_DRAFTS_ENABLED
ENV NEXT_PUBLIC_COMMAND_CENTER_V2=$NEXT_PUBLIC_COMMAND_CENTER_V2
ENV COURSE_PIPELINE_V2=$COURSE_PIPELINE_V2
ENV COURSE_VALIDATION_V2=$COURSE_VALIDATION_V2
ENV COURSE_REPAIR_V2=$COURSE_REPAIR_V2
ENV COURSE_LABS_V2=$COURSE_LABS_V2
ENV COURSE_VISUALS_V2=$COURSE_VISUALS_V2
ENV COURSE_PUBLICATION_V2=$COURSE_PUBLICATION_V2
ENV COURSE_PIPELINE_SHADOW_MODE=$COURSE_PIPELINE_SHADOW_MODE
ENV COURSE_PIPELINE_V2_OWNER_ONLY=$COURSE_PIPELINE_V2_OWNER_ONLY
ENV COURSE_PIPELINE_V2_COHORT_PERCENT=$COURSE_PIPELINE_V2_COHORT_PERCENT
WORKDIR /app
RUN groupadd --system --gid 1001 nodejs \
  && useradd --system --uid 1001 --gid nodejs nextjs
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=production-dependencies --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/scripts/provision-azure-postgres-roles.ts ./scripts/provision-azure-postgres-roles.ts
COPY --from=builder --chown=nextjs:nodejs /app/scripts/migrate-azure-database.ts ./scripts/migrate-azure-database.ts
COPY --from=builder --chown=nextjs:nodejs /app/scripts/import-azure-authored-courses.ts ./scripts/import-azure-authored-courses.ts
COPY --from=builder --chown=nextjs:nodejs /app/scripts/verify-azure-authored-courses.ts ./scripts/verify-azure-authored-courses.ts
COPY --from=builder --chown=nextjs:nodejs /app/src/lib/document-values.ts ./src/lib/document-values.ts
COPY --from=builder --chown=nextjs:nodejs /app/infra/azure/database ./infra/azure/database
USER nextjs
EXPOSE 3000
CMD ["sh", "-c", "node --experimental-strip-types scripts/provision-azure-postgres-roles.ts && node --experimental-strip-types scripts/migrate-azure-database.ts && exec node server.js"]
