import type { Metadata } from "next";
import LegalDocument from "@/components/LegalDocument";

export const metadata: Metadata = { title: "Acceptable Use Policy | Erudoza", description: "Rules that protect Erudoza learners and the service." };

export default function AcceptableUsePage() {
  return <LegalDocument eyebrow="Safety" title="Acceptable Use Policy" summary="Use Erudoza for lawful learning. These boundaries protect learners, creators, and the systems that make the service available.">
    <section><h2>Allowed use</h2><p>You may use Erudoza to study lawful subjects, create courses you have the right to create, ask good-faith questions, take notes, practice recall, and publish appropriate educational material.</p></section>
    <section><h2>Prohibited content and conduct</h2><p>You may not use Erudoza to create, request, upload, publish, or distribute content or activity involving:</p><ul><li>child sexual abuse material, sexual content involving minors, grooming, exploitation, or trafficking;</li><li>credible threats, violent wrongdoing, weapon construction intended to harm, terrorism support, or instructions that materially facilitate serious injury;</li><li>hate, targeted harassment, stalking, doxxing, non-consensual intimate content, or encouragement of self-harm;</li><li>malware, credential theft, phishing, evasion, destructive code, unauthorized intrusion, or instructions to compromise systems;</li><li>fraud, impersonation, academic cheating presented as your own work, deceptive manipulation, spam, or coordinated inauthentic activity;</li><li>illegal drugs or other unlawful transactions, or instructions that meaningfully facilitate criminal conduct;</li><li>personal or confidential information you lack permission to use, biometric identification, or unlawful surveillance;</li><li>copyright, trademark, privacy, publicity, or other rights violations;</li><li>unqualified high-stakes medical, legal, financial, employment, housing, education-admissions, or safety decisions about another person;</li><li>attempts to bypass moderation, quotas, subscriptions, authorization, rate limits, or other safeguards.</li></ul></section>
    <section><h2>System integrity</h2><p>Do not scrape, crawl, benchmark, reverse engineer, overwhelm, disrupt, or probe Erudoza without written permission. Do not share tokens, inject instructions into course content to manipulate the tutor, submit automated requests outside documented interfaces, or obscure the origin of abusive activity.</p></section>
    <section><h2>Enforcement</h2><p>We may block a request, remove or unpublish content, limit generation, suspend an account, preserve evidence, or report conduct when reasonably necessary. We consider context, severity, repetition, intent, and risk. If you believe a decision was mistaken, contact us with the course or account details and a concise explanation.</p></section>
  </LegalDocument>;
}
