import assert from "node:assert/strict";
import { test, after } from "node:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { randomUUID } from "node:crypto";
import * as store from "../../src/lib/document-store.ts";
import * as operations from "../../src/lib/generation-operations.ts";
import { captureAccountGeneration, runWithAccountGeneration } from "../../src/lib/account-lifecycle.ts";
import { lessonCourseFingerprint, lessonPublicationState } from "../../src/lib/course-pipeline/lesson-save.ts";
import type { ServerAccount } from "../../src/lib/account-server.ts";
import { generationAccountingContext } from "../../src/lib/ai-usage.ts";
const directory = mkdtempSync(join(tmpdir(), "lesson-operations-"));
process.env.FILOSAGE_LOCAL_DIR = relative(process.cwd(), directory);
after(() => rmSync(directory, { recursive: true, force: true }));
async function fixture(uid: string = randomUUID()) {
  const scope = await captureAccountGeneration(uid);
  const owned = <T>(work: () => T) => runWithAccountGeneration(scope, work);
  const account: ServerAccount = { uid, isOwner: true, plan: "pro", access: "owner", accountStatus: "active", subscriptionStatus: "active" };
  const course = { authorId: uid, isPublic: false, modules: [{ lessons: [{ title: "One" }, { title: "Two" }] }] };
  await owned(() => store.putStoredDocument(`courses/${uid}`, course));
  const request = { courseId: uid, lessonId: "0-0", regenerate: false };
  const guard = { courseFingerprint: lessonCourseFingerprint(course, "0-0"), publicationState: lessonPublicationState(course), scopeVersion: 1 as const, invalidateReadiness: true };
  const key = `lesson-operation-${uid}`;
  const begin = (operationKey = key, now = new Date()) => owned(() => operations.beginGenerationOperation(account, operationKey, request, now, { kind: "lesson", lessonGuard: guard }));
  return { uid, scope, owned, account, course, request, guard, key, begin };
}
test("lesson admission retains planned grant and shares budgets with independent lesson locks", async () => {
  const f = await fixture();
  const first = await f.begin();
  assert.equal(first.operation.kind, "lesson");
  assert.equal(first.operation.accounting.periodPath.includes("lesson_generation"), true);
  assert.equal(await store.getStoredDocument(`users/${f.uid}/courseCredits/current`), null);
  const second = await f.owned(() => operations.beginGenerationOperation(f.account, `${f.key}-two`, { ...f.request, lessonId: "0-1" }, new Date(), { kind: "lesson", lessonGuard: { ...f.guard, courseFingerprint: lessonCourseFingerprint(f.course, "0-1") } }));
  assert.equal(first.operation.accounting.periodPath, second.operation.accounting.periodPath);
  assert.notEqual(first.operation.accounting.lockKey, second.operation.accounting.lockKey);
});
test("lesson status resumes saved paid stages without another provider call or reservation", async () => {
  const f = await fixture();
  const first = await f.begin();
  let calls = 0;
  const response = { id: "synthetic-response", usage: { input_tokens: 2, output_tokens: 2 }, output_parsed: { content: "Saved stage" } };
  const params = { model: "gpt-5.6-luna", input: "same request", text: { format: { name: "lesson" } } };
  await operations.runGenerationProviderCall(first, params, async () => { calls++; return response; });
  await operations.pauseGenerationOperation(first);
  const next = await f.begin();
  assert.notEqual(next.attemptToken, first.attemptToken);
  assert.deepEqual(await operations.runGenerationProviderCall(next, params, async () => { calls++; return response; }), response);
  assert.equal(calls, 1);
  assert.equal((await store.getStoredDocument(next.operation.accounting.periodPath))?.requestCount, 1);
  assert.deepEqual(next.operation.lessonGuard, first.operation.lessonGuard);
});
test("durable lesson result and original accounting finish atomically and recover without another call", async () => {
  const f = await fixture("lesson-commit-account");
  const peer = await fixture("lesson-shared-shard-peer");
  const now = new Date();
  const context = generationAccountingContext(f.account, operations.generationOperationId(f.uid, f.key, "lesson"), "lesson_generation", now);
  const peerKey = Array.from({ length: 1024 }, (_, index) => `${peer.key}-${index}`).find((key) =>
    generationAccountingContext(peer.account, operations.generationOperationId(peer.uid, key, "lesson"), "lesson_generation", now).globalPath === context.globalPath);
  assert.ok(peerKey, "The fixture must deliberately share a real budget shard.");
  const unrelatedReserved = Number((await store.getStoredDocument(context.globalPath))?.reservedCostMicros ?? 0);
  const peerLease = await peer.begin(peerKey, now);
  await operations.runGenerationProviderCall(peerLease, { model: "gpt-5.6-luna", input: "peer paid stage" }, async () => ({ id: "response-peer", usage: { input_tokens: 2, output_tokens: 2 } }));
  const peerReceipt = (await store.getStoredDocument(peerLease.receiptPath))!;
  assert.equal(peerReceipt.actualCostMicros, 14);
  assert.equal(peerReceipt.remainingReserveMicros, peerLease.operation.accounting.reserveCostMicros - 14);
  const retainedReserved = unrelatedReserved + Number(peerReceipt.remainingReserveMicros);
  assert.equal((await store.getStoredDocument(context.globalPath))?.reservedCostMicros, retainedReserved);
  const peerPaths = [peerLease.operationPath, peerLease.receiptPath, peerLease.operation.accounting.requestPath,
    peerLease.operation.accounting.periodPath, peerLease.operation.accounting.userBudgetPath];
  const peerDocuments = await Promise.all(peerPaths.map((path) => store.getStoredDocument(path)));
  const lease = await f.begin(f.key, now);
  assert.notEqual(lease.operation.uid, peerLease.operation.uid);
  assert.equal(lease.operation.accounting.globalPath, peerLease.operation.accounting.globalPath);
  await operations.runGenerationProviderCall(lease, { model: "gpt-5.6-luna", input: "lesson body" }, async () => ({ id: "response-commit", usage: { input_tokens: 4, output_tokens: 4 }, output_parsed: { content: "Confirmed stage" } }));
  const beforeCommit = (await store.getStoredDocument(context.globalPath))!;
  const ownReceipt = (await store.getStoredDocument(lease.receiptPath))!;
  assert.equal(beforeCommit.reservedCostMicros, retainedReserved + Number(ownReceipt.remainingReserveMicros));
  const reservation = operations.lessonOperationReservation(lease);
  const guard = { ...f.guard, actor: f.account, reservation, operation: lease, usage: { usageSamples: [] } };
  await f.owned(() => store.saveLesson(f.uid, "0-0", { authorId: f.uid, content: "Confirmed stage" }, guard));
  const operation = await operations.getGenerationOperation(f.uid, lease.operationId);
  assert.equal(operation?.status, "completed");
  assert.equal((await store.getStoredDocument(reservation.periodPath))?.reservedCostMicros, 0);
  assert.equal((await store.getStoredDocument(reservation.userBudgetPath))?.reservedCostMicros, 0);
  const committedGlobal = (await store.getStoredDocument(reservation.globalPath))!;
  assert.equal(committedGlobal.reservedCostMicros, retainedReserved);
  assert.equal(committedGlobal.actualCostMicros, beforeCommit.actualCostMicros);
  assert.equal((await store.getStoredDocument(lease.receiptPath))?.remainingReserveMicros, 0);
  assert.equal((await store.getStoredDocument(reservation.requestPath))?.actualCostMicros, (await store.getStoredDocument(lease.receiptPath))?.actualCostMicros);
  await operations.finishGenerationOperation(lease, { failed: true });
  assert.equal((await store.getStoredDocument(reservation.periodPath))?.requestCount, 1);
  assert.equal((await f.owned(() => store.recoverCommittedLesson(f.uid, "0-0", reservation))).content, "Confirmed stage");
  assert.deepEqual(await store.getStoredDocument(reservation.globalPath), committedGlobal);
  assert.deepEqual(await Promise.all(peerPaths.map((path) => store.getStoredDocument(path))), peerDocuments);
  await operations.finishGenerationOperation(peerLease, { failed: true });
  assert.equal((await store.getStoredDocument(reservation.globalPath))?.reservedCostMicros, unrelatedReserved);
});
test("pre-dispatch refusal removes only its unstarted intent and preserves prior paid checkpoints", async () => {
  const f = await fixture();
  const lease = await f.begin();
  const { EvaluationBudgetError } = await import("../../src/lib/evaluation-errors.ts");
  const response = { id: "known-fixture", usage: { input_tokens: 1, output_tokens: 1 } };
  await operations.runGenerationProviderCall(lease, { model: "gpt-5.6-luna", input: "paid-stage" }, async () => response);
  const params = { model: "gpt-5.6-luna", input: "not-dispatched" };
  await assert.rejects(operations.runGenerationProviderCall(lease, params, async () => { throw new EvaluationBudgetError("EVALUATION_BUDGET_EXHAUSTED"); }), EvaluationBudgetError);
  const saved = await operations.getGenerationOperation(f.uid, lease.operationId);
  assert.deepEqual(saved?.pendingCalls, []);
  const receipt = await store.getStoredDocument(lease.receiptPath);
  assert.equal(Object.keys(receipt!.calls as object).length, 1);
  await operations.pauseGenerationOperation(lease);
  const resumed = await f.begin();
  let calls = 0;
  await operations.runGenerationProviderCall(resumed, params, async () => { calls++; return response; });
  assert.equal(calls, 1);
});
test("an ambiguous lesson provider result is reconciled without replaying its paid call", async () => {
  const f = await fixture();
  const lease = await f.begin();
  let calls = 0;
  await assert.rejects(operations.runGenerationProviderCall(lease, { model: "gpt-5.6-luna", input: "lost-call" }, async () => { calls++; throw new Error("Synthetic response loss"); }), /unconfirmed/);
  const saved = (await operations.getGenerationOperation(f.uid, lease.operationId))!;
  await assert.rejects(f.owned(() => operations.beginGenerationOperation(f.account, f.key, f.request, new Date(Date.parse(saved.leaseUntil) + 1), { kind: "lesson", lessonGuard: f.guard })), /could not be confirmed/);
  assert.equal(calls, 1);
  assert.equal((await operations.getGenerationOperation(f.uid, lease.operationId))?.status, "failed");
  const receipt = await store.getStoredDocument(lease.receiptPath);
  assert.ok(Number(receipt?.uncertainCostMicros) > 0);
  assert.equal((await store.getStoredDocument(lease.operation.accounting.periodPath))?.reservedCostMicros, 0);
  assert.equal(await store.getStoredDocument(`users/${f.uid}/courseCredits/current`), null);
});
test("late lesson usage after account deletion cannot recreate private stage or lesson records", async () => {
  const f = await fixture();
  const lease = await f.begin();
  let release!: (value: { id: string; usage: { input_tokens: number; output_tokens: number } }) => void;
  let started!: () => void;
  const ready = new Promise<void>((resolve) => { started = resolve; });
  const response = new Promise<{ id: string; usage: { input_tokens: number; output_tokens: number } }>((resolve) => { release = resolve; });
  const pending = operations.runGenerationProviderCall(lease, { model: "gpt-5.6-luna", input: "late" }, () => { started(); return response; });
  const rejected = assert.rejects(pending, /account|generation/i);
  await ready;
  await f.owned(() => store.putStoredDocument(`accountLifecycles/${f.uid}`, { ...f.scope, state: "deleting" }));
  release({ id: "late-fixture", usage: { input_tokens: 3, output_tokens: 3 } });
  await rejected;
  assert.ok(Number((await store.getStoredDocument(lease.receiptPath))?.actualCostMicros) > 0);
  assert.equal(await store.getLesson(f.uid, "0-0"), null);
});

test("a replaced lesson attempt cannot checkpoint, finish, or clear its successor lock", async () => {
  const f = await fixture();
  const original = await f.begin();
  await operations.pauseGenerationOperation(original);
  const successor = await f.begin();
  let dispatches = 0;
  await assert.rejects(operations.runGenerationProviderCall(original, { model: "gpt-5.6-luna", input: "stale" }, async () => { dispatches++; return {}; }), /ownership/);
  await assert.rejects(operations.finishGenerationOperation(original, { failed: true }), /ownership/);
  assert.equal(dispatches, 0);
  const period = await store.getStoredDocument(successor.operation.accounting.periodPath);
  const locks = period!.resourceLocks as Record<string, { activeAttemptToken: string }>;
  assert.equal(locks[successor.operation.accounting.lockKey!].activeAttemptToken, successor.attemptToken);
  await operations.finishGenerationOperation(successor, { failed: true });
  await operations.finishGenerationOperation(successor, { failed: true });
  assert.equal((await store.getStoredDocument(successor.operation.accounting.periodPath))?.requestCount, 0);
  assert.equal((await store.getStoredDocument(successor.operation.accounting.userBudgetPath))?.reservedCostMicros, 0);
});
test("lesson recovery retains original accounting month and rejects payload or writer changes", async () => {
  const f = await fixture();
  const first = await f.begin();
  await operations.configureGenerationOperation(first, { writer: "lesson-fixture-v1" });
  await operations.pauseGenerationOperation(first);
  await assert.rejects(f.owned(() => operations.beginGenerationOperation(f.account, f.key, { ...f.request, regenerate: true }, new Date(), { kind: "lesson", lessonGuard: f.guard })), /different request/);
  // The saved original period is authoritative even after a monthly rollover.
  const rollover = new Date(); rollover.setUTCMonth(rollover.getUTCMonth() + 1, 1);
  const paused = (await operations.getGenerationOperation(f.uid, first.operationId))!;
  await f.owned(() => store.putStoredDocument(first.operationPath, { ...paused, updatedAt: rollover.toISOString() }));
  const next = await f.owned(() => operations.beginGenerationOperation(f.account, f.key, f.request, rollover, { kind: "lesson", lessonGuard: f.guard }));
  assert.deepEqual(next.operation.accounting, first.operation.accounting);
  await assert.rejects(operations.configureGenerationOperation(next, { writer: "lesson-fixture-v2" }), /original generation configuration/);
  await operations.finishGenerationOperation(next, { failed: true });
  assert.equal((await store.getStoredDocument(first.operation.accounting.periodPath))?.requestCount, 0);
});

test("late confirmed lesson usage reconciles its immutable attempt and request exactly once", async () => {
  const f = await fixture();
  const lease = await f.begin();
  let release!: (value: { id: string; usage: { input_tokens: number; output_tokens: number } }) => void;
  let started!: () => void;
  const ready = new Promise<void>((resolve) => { started = resolve; });
  const response = new Promise<{ id: string; usage: { input_tokens: number; output_tokens: number } }>((resolve) => { release = resolve; });
  const pending = operations.runGenerationProviderCall(lease, { model: "gpt-5.6-luna", input: "late-confirmed" }, () => { started(); return response; });
  const rejected = assert.rejects(pending, /ownership/);
  await ready;
  await operations.finishGenerationOperation(lease, { failed: true, reason: "provider_outcome_unknown", reconcile: true }, new Date(Date.parse(lease.operation.leaseUntil) + 1));
  const successor = await f.owned(() => operations.beginGenerationOperation(f.account, `${f.key}-successor`, f.request, new Date(), { kind: "lesson", lessonGuard: f.guard }));
  release({ id: "late-confirmed", usage: { input_tokens: 100, output_tokens: 100 } });
  await rejected;
  const requestPath = lease.operation.accounting.requestPath;
  const attemptPath = `aiRequests/${lease.operationId}__attempt__${lease.attemptToken}`;
  const request = (await store.getStoredDocument(requestPath))!;
  const attempt = (await store.getStoredDocument(attemptPath))!;
  const receipt = (await store.getStoredDocument(lease.receiptPath))!;
  for (const record of [request, attempt]) {
    assert.equal(record.actualCostMicros, receipt.actualCostMicros);
    assert.equal(record.uncertainCostMicros, 0);
    assert.equal(record.inputTokens, 100);
    assert.equal(record.outputTokens, 100);
  }
  const period = (await store.getStoredDocument(lease.operation.accounting.periodPath))!;
  assert.equal(period.actualCostMicros, receipt.actualCostMicros);
  assert.equal(period.inputTokens, 100);
  assert.equal((period.resourceLocks as Record<string, { activeAttemptToken: string }>)[successor.operation.accounting.lockKey!].activeAttemptToken, successor.attemptToken);
  const failed = (await operations.getGenerationOperation(f.uid, lease.operationId))!;
  await operations.reconcileGenerationOperation(failed, true);
  await operations.finishGenerationOperation(lease, { failed: true });
  assert.deepEqual(await store.getStoredDocument(requestPath), request);
  assert.deepEqual(await store.getStoredDocument(attemptPath), attempt);
  assert.deepEqual(await store.getStoredDocument(lease.operation.accounting.periodPath), period);
});
