import assert from "node:assert/strict";
import { after, test, mock } from "node:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { captureAccountGeneration, runWithAccountGeneration } from "../../src/lib/account-lifecycle.ts";
import { putStoredDocument, getStoredDocument, getLesson } from "../../src/lib/document-store.ts";
import { POST as generateCourse } from "../../src/app/api/generate-course/route.ts";
import { POST as generateLesson } from "../../src/app/api/generate-lesson/route.ts";
import { TERMS_VERSION, PRIVACY_VERSION } from "../../src/lib/legal.ts";
if (process.env.OPENAI_API_KEY || process.env.DATABASE_URL || process.env.NODE_ENV === "production") throw new Error("Lesson route fixtures require isolated local mode without provider keys.");
const directory = mkdtempSync(join(tmpdir(), "lesson-route-"));
process.env.FILOSAGE_LOCAL_DIR = relative(process.cwd(), directory);
after(() => rmSync(directory, { recursive: true, force: true }));
const request = (path: string, key: string, body: unknown) => new Request(`https://fixture.invalid/api/${path}`, { method: "POST", headers: { Authorization: "Bearer local-dev-token", "Content-Type": "application/json", "Idempotency-Key": key }, body: JSON.stringify(body) });
import { aiClient } from "../../src/lib/local-ai.ts";
import { lessonGenerationConfiguration } from "../../src/lib/lesson-generation-configuration.ts";
import { generationFingerprint } from "../../src/lib/generation-operations.ts";
import { GET as status, POST as resume } from "../../src/app/api/generation-operations/[operationId]/route.ts";
for (const slowRepair of [false, true]) test(`actual SDK lesson route ${slowRepair ? "resumes a slow observed schema repair" : "resumes checkpoints"} and charges the approved tariff exactly once`, async () => {
  const scope = await captureAccountGeneration("local-owner");
  const owned = <T>(work: () => T) => runWithAccountGeneration(scope, work);
  await owned(() => putStoredDocument("users/local-owner", { uid: "local-owner", plan: "pro", accountStatus: "active", acceptedTermsVersion: TERMS_VERSION, acceptedPrivacyVersion: PRIVACY_VERSION }));
  const outline = await generateCourse(request("generate-course", `lesson-route-outline-${slowRepair}`, { topic: "Scientific reasoning", goal: "Compare evidence behind everyday claims.", language: "English" }));
  const outlineBody = await outline.json();
  assert.equal(outline.status, 200, JSON.stringify(outlineBody));
  // The local lesson fixture uses this deterministic objective. Align the
  // synthetic course plan; provider pedagogical calibration is outside this test.
  const course = await getStoredDocument(`courses/${outlineBody.courseId}`);
  const modules = course!.modules as Array<{ lessons: Array<Record<string, unknown>> }>;
  const objective = `Apply ${String(modules[0].lessons[0].concept).toLowerCase()} to a new situation and explain the reasoning behind each step.`;
  modules[0].lessons[0].objective = objective;
  const design = course!.learningDesign as { lessonPlans: Array<{ lessonId: string; scopeBudget: Record<string, unknown> }> };
  const plan = design.lessonPlans.find((item) => item.lessonId === "0-0")!;
  plan.scopeBudget.singleWin = objective;
  plan.scopeBudget.explanationWordLimit = 650;
  await owned(() => putStoredDocument(`courses/${outlineBody.courseId}`, { ...course, modules, learningDesign: design }));
  const payload = { courseId: outlineBody.courseId, lessonId: "0-0" };
  const local = aiClient();
  process.env.OPENAI_API_KEY = "synthetic-sdk-lesson-key";
  process.env.SITE_VERSION = "a".repeat(40);
  const configuration = lessonGenerationConfiguration({ uid: "local-owner", isOwner: true }, false);
  const rate = { maxInputTokens: 1_000_000, maxOutputTokens: 100_000, inputMicrosPerMillion: 0, cachedInputMicrosPerMillion: 0, cacheWriteInputMicrosPerMillion: 0, outputMicrosPerMillion: 1_000_000, maxToolCalls: 0, webSearchCallMicros: 0 };
  process.env.FILOSAGE_MODEL_EVALUATION_APPROVAL = JSON.stringify({ version: 1, uid: "local-owner", buildSha: "a".repeat(40), profile: "lesson-sdk-fixture", operationCeilingMicros: 100_000, expiresAt: "2099-01-01T00:00:00Z", rateVersion: "synthetic-lesson-tariffs", configurationFingerprints: { course: generationFingerprint(configuration), lesson: generationFingerprint(configuration) }, models: Object.fromEntries(configuration.profiles.map((p) => [p.model, rate])), moderation: { model: "omni-moderation-latest", maxInputBytes: 1_000_000, requestCostMicros: 7 } });
  const headers = { Authorization: "Bearer local-dev-token", "Content-Type": "application/json", "Idempotency-Key": `sdk-lesson-operation-${slowRepair}`, "x-filosage-model-evaluation": "1", "x-filosage-evaluation-build-sha": "a".repeat(40), "x-filosage-evaluation-profile": "lesson-sdk-fixture", "x-filosage-evaluation-max-cost-micros": "100000" };
  let dispatches = 0;
  let responses = 0;
  let clock = Date.now();
  const transport = mock.method(globalThis, "fetch", async (input: string | URL | Request, init?: RequestInit) => {
    dispatches++;
    const body = JSON.parse(String(init?.body));
    let result: Response;
    if (String(input).endsWith("/moderations")) result = Response.json({ id: `modr-${dispatches}`, model: "omni-moderation-latest", results: [{ flagged: false }] });
    else {
      assert.match(String(input), /\/responses$/);
      responses++;
      const fixture = await local.responses.parse(body);
      const raw = fixture.output_parsed as unknown as { visuals?: unknown[]; interactions?: unknown[] };
      raw.visuals = [];
      raw.interactions = [];
      if (slowRepair && responses === 1) (raw as { content?: string }).content = "Too short.";
      result = Response.json({ id: `resp_${dispatches}`, object: "response", service_tier: "default", status: "completed", model: body.model, output: [{ id: "msg-fixture", type: "message", role: "assistant", status: "completed", content: [{ type: "output_text", text: JSON.stringify(fixture.output_parsed), annotations: [] }] }], usage: { input_tokens: 10, output_tokens: 10, input_tokens_details: { cached_tokens: 0, cache_write_tokens: 0 } } });
    }
    // Cross the bounded-wave boundary without waiting or making network calls.
    clock += slowRepair ? 36_000 : 6_000;
    mock.timers.reset();
    mock.timers.enable({ apis: ["Date"], now: clock });
    return result;
  });
  try {
    const start = await generateLesson(new Request("https://fixture.invalid/api/generate-lesson", { method: "POST", headers, body: JSON.stringify(payload) }));
    const started = await start.json();
    assert.equal(start.status, 202, JSON.stringify(started));
    assert.equal(started.evaluation.actualCostMicros, 7);
    const context = { params: Promise.resolve({ operationId: started.operationId }) };
    const beforeUnapprovedResume = await getStoredDocument(`generationOperations/${started.operationId}`);
    const ordinaryHeaders = { Authorization: "Bearer local-dev-token", "Content-Type": "application/json" };
    const unapproved = await resume(new Request(`https://fixture.invalid/api/generation-operations/${started.operationId}`, { method: "POST", headers: ordinaryHeaders }), context);
    const unapprovedBody = await unapproved.json();
    assert.equal(unapproved.status, 409, JSON.stringify(unapprovedBody));
    assert.equal(unapprovedBody.code, "EVALUATION_APPROVAL_REQUIRED");
    assert.deepEqual(await getStoredDocument(`generationOperations/${started.operationId}`), beforeUnapprovedResume);
    assert.equal(dispatches, 1, "Omitting evaluation headers cannot escape the approved cap.");
    const second = await resume(new Request(`https://fixture.invalid/api/generation-operations/${started.operationId}`, { method: "POST", headers }), context);
    const resumed = await second.json();
    assert.equal(second.status, 202, JSON.stringify(resumed));
    assert.equal(resumed.code, "GENERATION_RESUME_REQUIRED", JSON.stringify(resumed));
    assert.equal(resumed.evaluation.actualCostMicros, 17, JSON.stringify(resumed));
    let third = await resume(new Request(`https://fixture.invalid/api/generation-operations/${started.operationId}`, { method: "POST", headers }), context);
    if (slowRepair) {
      const repairWave = await third.json();
      assert.equal(third.status, 202, JSON.stringify(repairWave));
      assert.equal(repairWave.evaluation.actualCostMicros, 27);
      third = await resume(new Request(`https://fixture.invalid/api/generation-operations/${started.operationId}`, { method: "POST", headers }), context);
    }
    const complete = await third.json();
    const expectedDispatches = slowRepair ? 4 : 3;
    const expectedCost = slowRepair ? 34 : 24;
    assert.equal(third.status, 200, JSON.stringify(complete));
    assert.equal(complete.status, "completed");
    assert.equal(typeof complete.resultId, "string");
    assert.equal(dispatches, expectedDispatches);
    assert.equal(responses, slowRepair ? 2 : 1);
    assert.equal(complete.evaluation.actualCostMicros, expectedCost);
    assert.deepEqual(complete.evaluation.calls.map((c: { kind: string }) => c.kind).sort(), [...(slowRepair ? ["fallback"] : []), "generation", "moderation", "moderation"]);
    const finalLesson = await getLesson(payload.courseId, payload.lessonId);
    assert.ok(finalLesson?.generationSafetyProof, "The synthetic SDK moderation receipt exercises final-payload proof creation.");
    const receipt = await getStoredDocument(`generationUsageReceipts/${started.operationId}`);
    const accounting = await getStoredDocument(`aiRequests/${started.operationId}`);
    assert.equal(receipt?.actualCostMicros, expectedCost);
    assert.equal(accounting?.actualCostMicros, expectedCost);
    const read = await status(new Request(`https://fixture.invalid/api/generation-operations/${started.operationId}`, { headers }), context);
    assert.equal(read.status, 200);
    assert.equal((await read.json()).evaluation.actualCostMicros, expectedCost);
    const replay = await resume(new Request(`https://fixture.invalid/api/generation-operations/${started.operationId}`, { method: "POST", headers }), context);
    assert.equal(replay.status, 200);
    assert.equal((await replay.json()).recovered, true);
    assert.equal(dispatches, expectedDispatches);
    const approval = JSON.parse(process.env.FILOSAGE_MODEL_EVALUATION_APPROVAL!);
    approval.operationCeilingMicros = 7;
    process.env.FILOSAGE_MODEL_EVALUATION_APPROVAL = JSON.stringify(approval);
    const changedApprovalRead = await status(new Request(`https://fixture.invalid/api/generation-operations/${started.operationId}`, { headers: { ...headers, "x-filosage-evaluation-max-cost-micros": "7" } }), context);
    assert.equal(changedApprovalRead.status, 409);
    assert.equal((await changedApprovalRead.json()).code, "EVALUATION_CONFIGURATION_CHANGED");
    const changedApprovalReplay = await resume(new Request(`https://fixture.invalid/api/generation-operations/${started.operationId}`, { method: "POST", headers: { ...headers, "x-filosage-evaluation-max-cost-micros": "7" } }), context);
    const rejectedReplay = await changedApprovalReplay.json();
    assert.equal(changedApprovalReplay.status, 409);
    assert.equal(rejectedReplay.operationId, started.operationId);
    assert.equal(rejectedReplay.code, "EVALUATION_CONFIGURATION_CHANGED");
    assert.equal(rejectedReplay.evaluation, undefined);
    assert.equal(dispatches, expectedDispatches);
    const limitedHeaders = { ...headers, "Idempotency-Key": `sdk-lesson-cap-refusal-${slowRepair}`, "x-filosage-evaluation-max-cost-micros": "7" };
    const limited = await generateLesson(new Request("https://fixture.invalid/api/generate-lesson", { method: "POST", headers: limitedHeaders, body: JSON.stringify({ ...payload, regenerate: true }) }));
    const limitedBody = await limited.json();
    assert.equal(limited.status, 202, JSON.stringify(limitedBody));
    const limitedContext = { params: Promise.resolve({ operationId: limitedBody.operationId }) };
    const refused = await resume(new Request(`https://fixture.invalid/api/generation-operations/${limitedBody.operationId}`, { method: "POST", headers: limitedHeaders }), limitedContext);
    const refusal = await refused.json();
    assert.equal(refused.status, 409, JSON.stringify(refusal));
    assert.equal(refusal.code, "EVALUATION_BUDGET_EXHAUSTED");
    assert.equal(refusal.evaluation.actualCostMicros, 7);
    assert.equal(refusal.evaluation.uncertainCostMicros, 0);
    assert.equal(dispatches, expectedDispatches + 1, "The rejected generation never reaches the transport.");
    const refusedOperation = await getStoredDocument(`generationOperations/${limitedBody.operationId}`);
    assert.deepEqual(refusedOperation?.pendingCalls, []);
    assert.equal(refusedOperation?.status, "failed");
    assert.equal((await getStoredDocument(`generationUsageReceipts/${limitedBody.operationId}`))?.actualCostMicros, 7);
    assert.deepEqual(await getLesson(payload.courseId, payload.lessonId), finalLesson);
  } finally {
    transport.mock.restore(); mock.timers.reset(); delete process.env.OPENAI_API_KEY; delete process.env.FILOSAGE_MODEL_EVALUATION_APPROVAL;
  }
});
