import assert from "node:assert/strict";
import { after, test } from "node:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { captureAccountGeneration, runWithAccountGeneration } from "../../src/lib/account-lifecycle.ts";
import { putStoredDocument, getStoredDocument, getLesson } from "../../src/lib/document-store.ts";
import { POST as generateCourse } from "../../src/app/api/generate-course/route.ts";
import { POST as generateLesson } from "../../src/app/api/generate-lesson/route.ts";
import { aiUsageRequestId, reserveAiUsage, finalizeAiUsage } from "../../src/lib/ai-usage.ts";
import { TERMS_VERSION, PRIVACY_VERSION } from "../../src/lib/legal.ts";
if (process.env.OPENAI_API_KEY || process.env.DATABASE_URL || process.env.NODE_ENV === "production") throw new Error("Lesson route fixtures require isolated local mode without provider keys.");
const directory = mkdtempSync(join(tmpdir(), "lesson-route-"));
process.env.FILOSAGE_LOCAL_DIR = relative(process.cwd(), directory);
after(() => rmSync(directory, { recursive: true, force: true }));
const request = (path: string, key: string, body: unknown) => new Request(`https://fixture.invalid/api/${path}`, { method: "POST", headers: { Authorization: "Bearer local-dev-token", "Content-Type": "application/json", "Idempotency-Key": key }, body: JSON.stringify(body) });
test("actual legacy route commits accounting and recovers only its exact local-stub result", async () => {
  const scope = await captureAccountGeneration("local-owner");
  const owned = <T>(work: () => T) => runWithAccountGeneration(scope, work);
  await owned(() => putStoredDocument("users/local-owner", { uid: "local-owner", plan: "pro", accountStatus: "active", acceptedTermsVersion: TERMS_VERSION, acceptedPrivacyVersion: PRIVACY_VERSION }));
  const outline = await generateCourse(request("generate-course", "lesson-route-outline", { topic: "Scientific reasoning", goal: "Compare evidence behind everyday claims.", language: "English" }));
  const outlineBody = await outline.json();
  assert.equal(outline.status, 200, JSON.stringify(outlineBody));
  // The local lesson fixture uses this deterministic objective. Align the
  // synthetic course plan; provider pedagogical calibration is outside this test.
  const course = await getStoredDocument(`courses/${outlineBody.courseId}`);
  const modules = course!.modules as Array<{ lessons: Array<Record<string, unknown>> }>;
  const objective = `Apply ${String(modules[0].lessons[0].concept).toLowerCase()} to a new situation and explain the reasoning behind each step.`;
  modules[0].lessons[0].objective = objective;
  const design = course!.learningDesign as { lessonPlans: Array<{ lessonId: string; scopeBudget: Record<string, unknown> }> };
  const plan = design.lessonPlans.find((item) => item.lessonId === "0-0")!;
  plan.scopeBudget.singleWin = objective;
  plan.scopeBudget.explanationWordLimit = 650;
  await owned(() => putStoredDocument(`courses/${outlineBody.courseId}`, { ...course, modules, learningDesign: design }));
  const payload = { courseId: outlineBody.courseId, lessonId: "0-0" };
  const key = "lesson-route-content";
  const lesson = await generateLesson(request("generate-lesson", key, payload));
  const body = await lesson.json();
  assert.equal(lesson.status, 200, JSON.stringify(body));
  const saved = await getLesson(payload.courseId, payload.lessonId);
  assert.ok(saved?.content);
  assert.equal(saved?.generationSafetyProof, undefined, "Local stub output cannot mint real moderation proof.");
  const operation = await getStoredDocument(`aiRequests/${await aiUsageRequestId("local-owner", "lesson_generation", key)}`);
  assert.equal(operation?.status, "completed");
  assert.ok(operation?.lessonResult);
  const replay = await generateLesson(request("generate-lesson", key, payload));
  assert.equal(replay.status, 200);
  assert.equal((await replay.json()).recovered, true);
  const failedKey = "lesson-route-failed-key";
  const failed = await owned(() => reserveAiUsage({ uid: "local-owner", isOwner: true, access: "owner", plan: "pro", accountStatus: "active", subscriptionStatus: "active" }, "lesson_generation", failedKey, `${payload.courseId}:${payload.lessonId}:generate`, { resourceKey: `${payload.courseId}:${payload.lessonId}` }));
  await owned(() => finalizeAiUsage(failed, { failed: true, usageSamples: [{ model: "gpt-5.6-luna", inputTokens: 0, cachedInputTokens: 0, cacheWriteTokens: 0, outputTokens: 0 }] }));
  const plainFailedRetry = await generateLesson(request("generate-lesson", failedKey, payload));
  assert.equal(plainFailedRetry.status, 409, JSON.stringify(await plainFailedRetry.clone().json()));
  assert.equal((await plainFailedRetry.json()).code, "IDEMPOTENCY_RESULT_SUPERSEDED");
  assert.equal((await getStoredDocument(failed.requestPath))?.status, "failed", "A plain retry must not admit or spend on an unintended replacement.");
  assert.deepEqual(await getLesson(payload.courseId, payload.lessonId), saved);
  await owned(() => putStoredDocument(`courses/${payload.courseId}/lessons/${payload.lessonId}`, { ...saved, content: "Later author content" }));
  const superseded = await generateLesson(request("generate-lesson", key, payload));
  assert.equal(superseded.status, 409);
  assert.equal((await superseded.json()).code, "IDEMPOTENCY_RESULT_SUPERSEDED");
});
