import type { Metadata } from "next";
import LegalDocument from "@/components/LegalDocument";
import { SUPPORT_CONTACT } from "@/lib/legal";

export const metadata: Metadata = { title: "Terms of Service | Erudoza", description: "The terms that govern use of Erudoza." };

export default function TermsPage() {
  return <LegalDocument eyebrow="Legal" title="Terms of Service" summary="These terms govern your access to Erudoza, including public lessons, learner accounts, course tools, AI-assisted features, and any future paid subscription.">
    <section><h2>1. Agreement and operator</h2><p>These Terms form a binding agreement between you and Erudoza, the operator of erudoza.com and the Erudoza learning service (“Erudoza,” “we,” “us,” or “our”). By creating an account, clicking to accept, purchasing a subscription, or using an account-only feature, you agree to these Terms and the <a href="/acceptable-use">Acceptable Use Policy</a>. The <a href="/privacy">Privacy Notice</a> explains our data practices. If you do not agree, do not create an account or use account-only features; you may still read public material where available.</p></section>
    <section><h2>2. Eligibility</h2><p>You must be at least 13 years old to use an account. By registering, you confirm that you meet this minimum age and, if you are under the age of legal majority where you live, that a parent or legal guardian has reviewed and agreed to these Terms for you. Erudoza is a general-audience service, is not directed to children under 13, and is not offered as a school-controlled education service. If we learn that an account belongs to a child under 13, we may suspend the account and delete associated information unless verified parental consent and other legally required controls are in place. You represent that the information you provide is accurate and that you are permitted to use the Google account you select.</p></section>
    <section><h2>3. Accounts and security</h2><p>You are responsible for activity under your account and for protecting access to your Google account and devices. Email <a href={`mailto:${SUPPORT_CONTACT}`}>{SUPPORT_CONTACT}</a> promptly if you suspect unauthorized access. You may not share access to evade plan limits, impersonate another person, resell an account, or use automated means to create accounts.</p></section>
    <section><h2>4. Learning service and AI-assisted content</h2><p>Erudoza provides courses, lessons, retrieval practice, notes, progress tracking, and AI-assisted course and tutor features. The product identifies direct AI interactions and AI-assisted learning material where applicable. AI output can be incomplete, inaccurate, outdated, or unsuitable for your circumstances. It is educational support, not professional advice or an autonomous decision about you. Verify important information and consult a qualified professional for medical, legal, financial, safety-critical, or other high-stakes decisions. Erudoza does not guarantee grades, credentials, employment, mastery, or any particular outcome.</p></section>
    <section><h2>5. Public and user-created courses</h2><p>Published courses are provided for personal, non-exclusive, non-transferable, read-only educational use unless a separate license says otherwise. Course creators retain rights they already hold in their submissions. By submitting content, you grant Erudoza a worldwide, non-exclusive, royalty-free license to host, reproduce, format, moderate, display, and distribute it only as needed to operate, secure, promote, and improve the service. You confirm that you have the rights needed to submit and publish it. We may unpublish, restrict, or remove content that is unlawful, unsafe, misleading, infringing, low quality, or inconsistent with these Terms. Our <a href="/copyright">Copyright Policy</a> explains our notice process and repeat-infringer policy.</p></section>
    <section><h2>6. Acceptable use</h2><p>You must follow our Acceptable Use Policy. You may not probe or bypass security, quotas, moderation, access controls, or billing controls; scrape the service at scale; interfere with other users; upload malicious code; misuse personal data; or use Erudoza to create prohibited, deceptive, exploitative, or infringing material. We may investigate abuse and preserve relevant records where legally permitted.</p></section>
    <section><h2>7. Plans, fees, and automatic renewal</h2><p>Free features may have limits. Before any paid purchase, checkout will show the price, currency, billing interval, included features, material limitations, trial terms if any, taxes where applicable, renewal terms, and how to cancel. A paid subscription will renew automatically for the stated interval until canceled. We will obtain your express consent before charging you and provide a receipt or acknowledgment containing the material terms. You may cancel through the same online account experience used to subscribe, or another simple method we identify at checkout. Cancellation stops future renewal and normally takes effect at the end of the paid period; access continues until then unless law requires otherwise.</p><p>We may change a future price or material subscription term only with advance notice and any consent required by law. Renewal and trial reminders will be provided where required. Except where law or a specific offer requires a refund, fees already paid are non-refundable and unused time or credits do not roll over. Paid checkout is not currently enabled; this section applies when it launches. Questions about plans, billing, cancellation, or refunds can be sent to <a href={`mailto:${SUPPORT_CONTACT}`}>{SUPPORT_CONTACT}</a>.</p></section>
    <section><h2>8. Intellectual property</h2><p>Erudoza and its software, branding, design, documentation, and original content are protected by intellectual-property laws. Except for the limited rights granted here, no rights are transferred to you. You may not copy, sell, reverse engineer, remove notices from, or create a competing service from protected parts of Erudoza except where law expressly permits. Feedback you voluntarily provide may be used without restriction or compensation.</p></section>
    <section><h2>9. Third-party services</h2><p>Erudoza relies on providers such as Google and Firebase for authentication and data infrastructure, OpenAI for AI-assisted features, hosting and network providers, and, when billing launches, a payment processor such as Stripe. Their services may have separate terms and may be unavailable from time to time. We are not responsible for third-party products you choose to access outside Erudoza.</p></section>
    <section><h2>10. Suspension and termination</h2><p>You may stop using Erudoza at any time. We may suspend or terminate access, remove content, or limit features when reasonably necessary to protect users or the service, respond to legal obligations, prevent harm or fraud, address nonpayment, or enforce these Terms. Where practical, we will give notice and an opportunity to cure. Provisions that by their nature should survive termination, such as ownership, disclaimers, liability limits, indemnity, and dispute terms, remain in effect.</p></section>
    <section><h2>11. Disclaimers</h2><p>To the maximum extent permitted by law, Erudoza is provided “as is” and “as available.” We disclaim implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, and uninterrupted availability. We do not warrant that every error or harmful use will be prevented. Some jurisdictions do not allow certain disclaimers, so parts of this section may not apply to you.</p></section>
    <section><h2>12. Limitation of liability</h2><p>To the maximum extent permitted by law, Erudoza and its creator, affiliates, contractors, and providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or loss of data, profits, revenue, goodwill, or opportunity. Our total liability for all claims arising from the service will not exceed the greater of US $100 or the amount you paid Erudoza during the 12 months before the event giving rise to the claim. These limits do not apply where prohibited or to liability that cannot lawfully be limited.</p></section>
    <section><h2>13. Indemnity</h2><p>To the extent permitted by law, you will defend, indemnify, and hold harmless Erudoza and its creator, affiliates, contractors, and providers from third-party claims, damages, and reasonable costs arising from your unlawful content, your material breach of these Terms, or your misuse of the service. This obligation does not apply to the extent a claim was caused by Erudoza.</p></section>
    <section><h2>14. Changes, notices, and service changes</h2><p>We may improve, change, or discontinue features. If we materially change these Terms, we will post the new version, update its effective date, and request renewed acceptance when appropriate. Changes do not retroactively alter rights already accrued. Notices may be provided in the service, by email, or through your account.</p></section>
    <section><h2>15. General terms</h2><p>These Terms and incorporated policies are the entire agreement about Erudoza. If one provision is unenforceable, the rest remains effective and the provision will be enforced to the maximum lawful extent. A failure to enforce a term is not a waiver. You may not assign this agreement without our consent; we may assign it as part of a reorganization, financing, or transfer of the service. Neither party is liable for delay caused by events reasonably beyond its control. Applicable law and courts will be those required by the law of the jurisdiction in which Erudoza&apos;s legal operator is established, subject to non-waivable consumer protections where you live. Paid subscriptions will remain disabled until the operator&apos;s formal identity, address, governing jurisdiction, and required consumer notices are disclosed.</p></section>
  </LegalDocument>;
}
