import test from 'node:test';import assert from 'node:assert/strict';
import {packageHostedProofs} from '../../scripts/package-candidate-proof.mjs';
import {fingerprint} from '../../scripts/blue-green-contract.ts';
import {hostedGates,validateHostedReview} from '../../scripts/blue-green-review.ts';
const candidate={sha:'b'.repeat(40),imageDigest:'sha256:'+'d'.repeat(64),revision:'app--candidate',appId:'app',manifest:{selection:true},authConfigSha256:'a'.repeat(64),productionOrigin:'https://filosage.com',previous:{sha:'c'.repeat(40),revision:'app--previous',image:'acr/filosage@sha256:'+'e'.repeat(64)}};
const artifact={runId:'123',artifactId:456,artifact:'release-candidate-'+candidate.sha,digest:'sha256:'+'f'.repeat(64)};
function packet(){return {schemaVersion:1,candidateFingerprint:fingerprint(candidate),evidence:hostedGates.map(gate=>{const source={reference:'task:reviewed-observation-'+gate,observations:[{check:'Actual '+gate+' check',expected:'Specified contract satisfied',observed:'Recorded concrete hosted observation',result:'passed'}]};return {gate,result:'passed',reviewedBy:'reviewer',method:'operator-reviewed',observedAt:'2026-09-13T00:00:00Z',source,sourceSha256:fingerprint(source)};})};}
test('seven immutable proof bodies preserve reviewed source and consumer identity',()=>{const proofs=packageHostedProofs(packet(),candidate,artifact);assert.equal(proofs.length,7);for(const {proof,source} of proofs){assert.equal(proof.result,'passed');assert.equal(proof.evidenceKind,'operator-reviewed');assert.equal(proof.automatedGateExecution,false);assert.deepEqual(proof.candidateArtifact,artifact);assert.equal(proof.sourceSha256,fingerprint(source));assert.equal(proof.sha,candidate.sha);}const review={schemaVersion:1,candidateFingerprint:fingerprint(candidate),operator:'operator',reviewedBy:'reviewer',rollbackTrigger:'Observed candidate regression',testDataPolicy:'approved-accounts-and-data-only',writeCompatibility:'overlapping-readers-writers-and-inflight-fences-verified',minimumSafeRollbackSha:candidate.previous.sha,rollbackRevision:candidate.previous.revision,rollbackImage:candidate.previous.image,rollbackAuthorized:true,evidence:proofs.map(({proof})=>({...proof,runId:'124',workflow:'.github/workflows/azure-candidate-evidence.yml',artifact:'proof-'+proof.gate,artifactDigest:'sha256:'+'1'.repeat(64)}))};validateHostedReview(review,candidate);});
test('identity mismatch, missing/duplicate gates and changed source hashes reject',()=>{for(const mutate of [p=>p.candidateFingerprint='0'.repeat(64),p=>p.evidence.pop(),p=>p.evidence[1]=p.evidence[0],p=>p.evidence[0].source.observations[0].observed='Changed after review']){const p=packet();mutate(p);assert.throws(()=>packageHostedProofs(p,candidate,artifact));}});
test('empty source, missing reviewer, future dates and failed observations cannot become passes',()=>{for(const mutate of [e=>e.source.observations=[],e=>e.reviewedBy='',e=>e.observedAt='2999-01-01T00:00:00Z',e=>e.source.observations[0].result='failed',e=>e.source.reference='',e=>e.source.observations[0].observed='']){const p=packet();mutate(p.evidence[0]);p.evidence[0].sourceSha256=fingerprint(p.evidence[0].source);assert.throws(()=>packageHostedProofs(p,candidate,artifact));}});

test('workflow uploads all seven proof directories only after packaging succeeds',async()=>{
 const {readFileSync}=await import('node:fs');const workflow=readFileSync('.github/workflows/azure-candidate-evidence.yml','utf8');
 assert.ok(workflow.includes('environment: azure-staging'));assert.ok(workflow.includes('group: azure-blue-green-${{ vars.AZURE_CONTAINER_APP_NAME }}'));
 const uploads=workflow.slice(workflow.indexOf('      - name: Retain reviewed'),workflow.indexOf('      - name: Remove only'));
 for(const gate of hostedGates){assert.ok(uploads.includes('name: candidate-proof-'+gate));assert.ok(uploads.includes('/hosted/'+gate+'/*.json'));}
 assert.equal(uploads.includes('if: always()'),false);assert.ok(workflow.indexOf('azure-blue-green.mjs package-evidence')<workflow.indexOf('name: candidate-proof-'));
});
